### PR TITLE
Broken arrays in promises fix with resultHandler option.

### PR DESCRIPTION
**Pull request by ivansglazunov**
This solution adds tihs each execution level a optional handler with possibility to wrap any object into promise, for example.

### CODE REVIEW

**Comment by ivansglazunov** [comment]
I can add description for `resultHandler`, into readme, if needed. Do I need to write a description for Promises?

**Comment by helfer** [comment]
@ivansglazunov I'm a bit confused. Can you explain how `resultHandler` is different from `resultMapper`?

**Comment by ivansglazunov** [comment]
As i say in issue, main problem was on the line https://github.com/apollographql/graphql-anywhere/blob/master/src/graphql.ts#L210. On this moment `Array.isArray` checks results from resolver, where returns promise. Because of this, any promise is executed as an object.

* `resultMapper` only works after execution, which follows from the name, it makes a map over the tree.
* `resultHandler` creates a handler between `resolver` and execution. This makes it possible to be sure that any data returned from the resolver will be understood correctly even before the entire tree is executed.

In fact, I wrapped the code https://github.com/apollographql/graphql-anywhere/blob/master/src/graphql.ts#L196-L218 in this handler, and now it receives the unpacked data and works currectly.

**Comment by ivansglazunov** [comment]
* I considered another option, to grasp Promise support out of the box, as here https://github.com/apollographql/graphql-anywhere/pull/51, but it seemed a bit ... not in the style of the library.

**Comment by helfer** [comment]
@ivansglazunov ok, I see what you mean now, but I don't think adding another function in there is the right approach. The current promise support is a bit hacky to begin with. We don't use it in apollo client, and so I'm be very hesitant to add more of it. However, I think we could soon make this library be standalone, in which case it would be a good idea to have promise support out of the box. For a graphql engine, I think that would be the natural thing to do anyway. Are you interested in working on that?

**Comment by ivansglazunov** [comment]
@helfer yes. Although now I'm a little confused. I would like to be able to independently explain for this library exactly how to perceive my data. Otherwise, you can ask why then `resultMapper`? You can say that  this has nothing to do with graphql at all, only post-processing and users can do the same thing yourself, do a map on the results tree manually.

This is a question of what this library looks like: 
* A set of tools for turning any query into any data is convenient.
* One small tool with clearly defined capabilities. (But why in it resultMapper?)

Sorry for this little sarcasm.

---

* In the same place where the `resultHandler`, need to do same work, but only if result isPromise.
  > Formally, we simply create an internal function handler for this, instead `resultHandler` from options. Although I usually advocate greater openness.
* The problem of the final result. If do not use `resultMapper`, the result is an object with Promises. The question arises:
  1. We can wrap all results on the first level in Promise as in graphql.js, and only after `then` use `resultMapper.
    > Feels like dictate. In some is possible without promises, but we require it.
  2. The user is forced to apply the resultMapper to the results independently, for a results wrap into promises.
    > For me, this is also a bit hack.

---

However, we can go the other way. Embed the default version for `resultHandler` и `resultMapper` with promises support. May be rename `resultHandler` to something? If, of course, go this "other way."

**Comment by jbaxleyiii** [comment]
I wanted to let everyone know that in the move to graphql-anywhere falling under the apollo-client repo, I will be taking a look at all of these PR's and may ask for you to recreate them in the new repo. I'm SO sorry this has been open for a while, one of the reasons for the move is to make sure PR's like this don't get missed by our team.

Thanks so much for contributing to this project btw! We want to continue to make it better and better with your help 🎉

**Comment by stubailo** [comment]
This repository has been moved into Apollo client, here: https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere

The equivalent of this PR there is: https://github.com/apollographql/apollo-client/pull/2670

**Pull request closed without merging**
