### PR TITLE
Deep merge arrays when merging fragment results

### PR DESCRIPTION
**Pull request by jesenko**
When merging arrays resulting from multiple fragments, only results from last
fragment were used, ignoring selectionsets from preceding fragments.

This commit changes behaviour of merge so that arrays are also deep-merged.

Related to #28, #29, https://github.com/apollostack/apollo-client/issues/1231

### CODE REVIEW

**Comment by helfer** [comment]
@jesenko Thanks for the PR! Could you split this up in a commit with a failing test first, and then the fix for it?

**Comment by jesenko** [comment]
@helfer Done!

**Comment by helfer** [comment]
@jesenko Thanks!

**Comment by jesenko** [comment]
@helfer Thanks for merging! I just checked - this also fixes apollographql/apollo-client#1231...

**Pull request merged**
