### PR TITLE
Add field node to ExecContext

### PR DESCRIPTION
**Pull request by brysgo**
This is useful for me because I can get access to directives.

Thoughts?

### CODE REVIEW

**Comment by stubailo** [comment]
Sure thing! Would it be better to just get directives though? That would probably look like `directives: { skip: { if: 'asdf' }, otherDirective: { arg: 'ert' } }`

We could probably reuse the current arguments to object function for that.

IMO if people have to work with the GraphQL AST directly then this package isn't doing its job. Thoughts?

**Comment by brysgo** [comment]
@stubailo - agreed! I'd be happy with a more curated approach.

**Comment by stubailo** [comment]
This will work for skip, include, etc, but if we want arbitrary directives to work with variables, nested objects, etc, we should use something similar to how we collect args from fields: https://github.com/apollographql/graphql-anywhere/blob/72d3ccf185d80c03213a319a535bfbcae64635cc/src/storeUtils.ts#L79

Sorry about the late response again, was super busy with the release.

**Comment by helfer** [comment]
Hey @brysgo, are you still interested in seeing this PR through? It looks like a little bit more work is required on directive parsing.

**Comment by brysgo** [comment]
@helfer - If I can find the time, though any help would be welcome.

**Comment by stubailo** [comment]
This looks great now!

**Pull request merged**
