### PR TITLE
Add promise support

### PR DESCRIPTION
**Pull request by brysgo**
Added promise support, seems to work pretty well, added a test.

I have a small project I'm working on that needs this so hopefully it makes it upstream.

#11

### CODE REVIEW

**Comment by stubailo** [comment]
A few preliminary comments:

1. Please remove `yarn.lock`, since it's not a good idea to have for libraries (although a great idea for apps!)
2. Can we also make sure the `fragmentMatcher` can be async?

**Comment by brysgo** [comment]
1. Absolutely, it just snuck in there and I usually don't bother fishing it out. Is there something I can read on why you wouldn't include a yarn.lock file in a library?

2. Sure.

**Comment by brysgo** [comment]
@stubailo - Anything else?

**Comment by brysgo** [comment]
I made a typescript noob mistake and added my fork as a dependency for brysgo/graphql-gun and now my tests are broken because typescript doesn't compile when it is a git dependency 😢

**Comment by stubailo** [comment]
Can you add a test for a field with nested arrays in it? I don't know if this will currently support, for example, a resolver that returns an array of promises. I don't think we need to support that at first, but we should at least document whether or not it works.

**Comment by brysgo** [comment]
@stubailo - I'm using a resolver that returns an array of promises https://github.com/brysgo/graphql-gun/blob/master/index.js#L73 :-)

but I agree we should add a test.

**Comment by stubailo** [comment]
Happy to accept the PR once there is a test, congrats on being in the front page of hacker news by the way!

**Comment by brysgo** [comment]
@stubailo thanks!

(also thanks for telling me about the hacker news post, I somehow missed it)

**Comment by brysgo** [comment]
@stubailo - I think you are right about the array bug, not sure why it didn't show up in `graphql-gun`.

**Comment by stubailo** [comment]
This looks great to me! My only concern is possible performance regressions in the synchronous case, hoping to put together a quick test for that soon. @helfer what are your thoughts here?

**Comment by brysgo** [comment]
@stubailo - I can tell you the time complexity hasn't increased for sure. I have an update that could let you write faster `promiseOrImmediate` and `arrayOrPromise` functions if you wanted to.

**Comment by brysgo** [comment]
I added an options to overwrite my two functions, specifically so I can play with subscribing at arbitrary points in the tree.

**Comment by brysgo** [comment]
@stubailo - here is my plan to eliminate any performance concerns:

1. Remove promise implementation from `graphql-anywhere`.
2. Create module called `async-passthrough` that implements the two functions at the bottom with a bunch of deferrables (including promises).

Thoughts?

**Comment by stubailo** [comment]
Hey sorry I haven't been on top of this - two things:

1. We're really interested in having an implementation like this, because it would be necessary for using some kinds of offline data stores that you can't read from synchronously. So very excited to work together to make this happen.
2. We're in the middle of a really big launch right now, so that's taking priority right now. In the coming days I should be able to do a quick performance test, it's likely that there are no problems at all with the current implementation.

Are you currently blocked, or is running off of a fork for a week or so OK for you?

**Comment by brysgo** [comment]
Not blocked, just thought I upset you :-)

**Comment by idibidiart** [comment]
@brysgo @stubailo 

hey guys, 

good work, I'm interested in this, too!

when it's finally merged can you please add some examples in the docs, too?

can't wait to try it out 

👍

**Comment by brysgo** [comment]
@stubailo - are we still tracking this? If so what are the next steps?

**Comment by idibidiart** [comment]
@brysgo would it be safe to use your fork of it for now? 

:) awesome stuff re: gun... just found out about it and if it uses GQL syntax for queries/mutations I'm sold! Thanks for this novel work! :) love it.

**Comment by brysgo** [comment]
@idibidiart - from the discussion in this thread I would say there is a high probability of this getting eventually merged, so it seems safe to use the fork.

graphql-gun however, is still fairly experimental, so I would say use it to play around but not for anything serious until I get the todo example working

**Comment by ehmicky** [comment]
For information, tslint is complaining about trailing commas (see Travis build).

**Comment by bwalex** [comment]
I'd also like graphql-anywhere to handle promises - my use case is resolving things from an IndexedDB database.

What is needed to progress this pull request and get it merged?

**Comment by brysgo** [comment]
@bwalex - I'm not sure, @stubailo might know what he still needs from us.

**Comment by idibidiart** [comment]
@stubailo if the concern is performance then could we make it so that it's opt-in? like config.async = true ?

**Comment by jbaxleyiii** [comment]
I wanted to let everyone know that in the move to graphql-anywhere falling under the apollo-client repo, I will be taking a look at all of these PR's and may ask for you to recreate them in the new repo. I'm SO sorry this has been open for a while, one of the reasons for the move is to make sure PR's like this don't get missed by our team.

Thanks so much for contributing to this project btw! We want to continue to make it better and better with your help 🎉

**Comment by sheerun** [comment]
I've published this branch as `@sheerun/graphql-anywhere`

**Comment by n1ru4l** [comment]
@jbaxleyiii This could be also very useful for https://github.com/n1ru4l/apollo-link-rest 🤗

**Comment by stubailo** [comment]
This repository has been moved into Apollo client, here: https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere

The equivalent of this PR there is: https://github.com/apollographql/apollo-client/pull/2670

**Pull request closed without merging**
